stages:
  - deploy

deploy:
  stage: deploy
  image: nikolaik/python-nodejs:python3.13-nodejs20
  before_script:
    - pip install aws-cdk-lib constructs
    - npm install -g aws-cdk
    - cd cdk-ec2
    - pip install -r requirements.txt
  script:
    - cdk synth
    - aws cloudformation deploy --template-file cdk.out/CdkEc2Stack.template.json --stack-name CdkEc2Stack --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
  variables:
    AWS_DEFAULT_REGION: us-east-1
  only:
    - mt